name = "glight"
version = "1.0.5"

description = "Logger library with multiple transports and structured logging data"
licences = ["MIT"]
repository = { type = "github", user = "distrill", repo = "glight" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
birl = ">= 1.8.0 and < 2.0.0"
file_streams = ">= 1.5.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
