name = "glight"
version = "2.1.1"

description = "Logger library with multiple transports and structured logging data"
licences = ["MIT"]
repository = { type = "github", user = "distrill", repo = "glight" }

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = ">= 0.62.0 and < 1.0.0"
birl = ">= 1.8.0 and < 2.0.0"
jsx = ">= 3.1.0 and < 4.0.0"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
